### ISSUE TITLE
CSS：テキスト装飾

### ISSUE THREAD

**Issue by mtur0605** [mtur0605/Note#22]
##テキスト装飾

###蛍光マーカー
![image](https://user-images.githubusercontent.com/102901930/233033495-c75c75bf-ca67-4f56-90db-81478a9c382b.png)
|:--|
``` CSS
.line-marker {
  background: linear-gradient(transparent 75%, #6cf 75%);
}
```
