### ISSUE TITLE
Sassでの@font-faceを使用したWEBフォントの読み込み

### ISSUE THREAD

**Issue by mtur0605** [mtur0605/Note#4]
### CSSでの記述（通常）
```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;500;600&display=swap');
```

### Sassでの記述
Sassでの@importがサポート終了により、「@font-face」を使用して読み込む必要がある。

```scss
@font-face {
  font-family: 'Noto Serif JP';
  src: url('https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;500;600&display=swap')
    format('opentype');
}
```

上記を foundation/_font.scss に記述。
