### ISSUE TITLE
Sass(2) : FLOCSSに基づいたファイル分割

### ISSUE THREAD

**Issue by mtur0605** [mtur0605/Note#5]
# Sassの記述形式

## ■ 基本の形

> HTML
``` html
<div class="sample">
    <h3>Title</h3>
    <div class="content">
        <p>paragraph</p>
        <p>paragraph</p>
    </div>
</div>
```
上記のようなHTMLの場合、
<br/>

> Sass
``` scss
.sample {
    border: 1px solid #999;
    background-color: #EEE;
    h3 {
        margin: 20px;
        font-size: 24px;
    }
    .content {
        p {
            color: green;
        }
}
```

Sassでは上記のように入れ子にしてスタイルを記述することが可能。
<br/>

> コンパイル後のCSS
```css
.sample {
    border: 1px solid #999;
    background-color: #EEE;
}
.sample h3 {
    margin: 20px;
    font-size: 24px;
}
.sample .content p {
    color: green;
}
```
コンパイル後、子孫セレクタで自動的に結合し上記のようになる。
<br/>
<br/>
## ■ 疑似クラス・疑似要素の場合（編集中）
> HTML
``` html
<div class="sample">
    <h3>Title</h3>
    <div class="content">
        <p>paragraph</p>
        <p>paragraph</p>
    </div>
</div>
```
テキスト〜〜テキスト〜〜テキスト〜〜
<br/>

> Sass
``` scss
.sample {
    border: 1px solid #999;
    background-color: #EEE;
    h3 {
        margin: 20px;
        font-size: 24px;
    }
    .content {
        p {
            color: green;
        }
}
```

テキスト〜〜テキスト〜〜テキスト〜〜
<br/>

> コンパイル後のCSS
```css
.sample {
    border: 1px solid #999;
    background-color: #EEE;
}
.sample h3 {
    margin: 20px;
    font-size: 24px;
}
.sample .content p {
    color: green;
}
```
テキスト〜〜テキスト〜〜テキスト〜〜

# ファイル分割（別Issue?）
