### ISSUE TITLE
Sass(4) : _mixins.scssの設定 + 置換

### ISSUE THREAD

**Issue by mtur0605** [mtur0605/Note#7]
# _mixins.scssの設定 + 置換

## メディアクエリのテンプレート

> _mixins.scss
``` scss
// 同じフォルダ内の variables.scss から変数を使用するので以下の記述
@use "variables" as var;

//? mq = メディアクエリ（任意名）
//? map-has-key: 配列の"key(キー)"を1つずつ取り出すための関数
//? var.$breakpoints = variables.scss 内の 変数$breakpoints（配列）を指す
//? $breakpoint: 配列から1つずつ取り出すために用意した箱（<別ファイル>内で "@include var.mq(sm){}" と記述した場合の "sm" が入る ）
//? inspect: ()内には調べたい引数の値を指定
//? map-get: 配列の"value（値）"を1つずつ取り出す（map-has-key とセット）
//? @content: <別ファイル> の @include ~~ { ここの内容全てを返す }

// ① 処理の箱を用意
@mixin mq($breakpoint) {
  // ② 例: 別ファイルの @include により、(例)"sm"が代入された場合に処理が行われる
  @if map-has-key(var.$breakpoints, $breakpoint) {
    // ③ inspect により、キーと値の関係をチェックする
    // ④ map-get により、キー"sm" に対応した値は "min-width: 576px" なのでその値を返す
    @media screen and #{inspect(map-get(var.$breakpoints, $breakpoint))} {
      // ⑤ @content により、(例)"sm"の場合のh1のスタイルを全て返す
      @content;
    }
  }
}
// ⑥ コンパイルすると、通常のCSSでメディアクエリを記述した書式で出力される
```

## フォントサイズのテンプレート
``` scss
@mixin font-size($size, $base: 16) {
  // IE対応にpx単位
  font-size: $size + px;
  // rem変換
  font-size: calc($size / $base) + rem;
}
```
